baseURL: "https://gorillamade.nl/"
languageCode: "nl"
title: "GorillaMade"

taxonomies:
  tag: "tags"
  category: "categories"

# -- Robots.txt en URL canonisatie --
enableRobotsTXT: true
canonifyURLs: true

# -- Samenvatting en emoji ondersteuning --
summaryLength: 70
enableEmoji: true

# -- Sitemap configuratie --
sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

# -- Languages --

defaultContentLanguage: nl
# languages:
#   nl:
#     contentDir: content
#     languageName: Nederlands
#     weight: 1