# -- Site Configuration --
baseURL: "https://gorillamade.nl/"
title: "GorillaMade"
# theme: "gm"

defaultContentLanguage: "nl"
defaultContentLanguageInSubdir: false

enableRobotsTXT: true
canonifyURLs: true

summaryLength: 120
enableEmoji: true

permalinks:
  showcases: "/showcases/:slug/"

pagination:
    pagerSize: 10

sitemap:
  changefreq: "monthly"
  priority: 0.5

rss:
  title: "GorillaMade - RSS Feed"
  link: "/rss.xml"

# -- Site Analytics --
params:
  analytics:
    google:
      enable: false
      id: "G-XXXXXXXXX"

    umami:
      enable: true
      website_id: "94bc3519-7ad0-4a66-924e-f7d3f99a26fa"
