# -- Site configuratie --
baseURL: 'https://gorillamade.nl/'
title: 'GorillaMade'


defaultContentLanguage: nl
defaultContentLanguageInSubdir: true

enableRobotsTXT: true
canonifyURLs: true

summaryLength: 70
enableEmoji: true

permalinks:
  services: "/diensten/:slug/"
  showcases: "/showcases/:slug/"