main:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "Over mij"
    pageRef: "/over-mij"
    weight: 20
  - name: "Showcases"
    pageRef: "/showcases"
    weight: 30
  - name: "Diensten"
    pageRef: "/diensten"
    weight: 40
  - name: "Branding"
    parent: "Diensten"
    pageRef: "/diensten/branding"
    weight: 10
  - name: "Websites"
    parent: "Diensten"
    pageRef: "/diensten/websites"
    weight: 20
  - name: "Hosting"
    parent: "Diensten"
    pageRef: "/diensten/hosting"
    weight: 30
  - name: "Zoekmachine optimalisatie"
    parent: "Diensten"
    pageRef: "/diensten/zoekmachine-optimalisatie"
    weight: 40
  - name: "CMS"
    parent: "Diensten"
    pageRef: "/diensten/content-management-system"
    weight: 50
  - name: "Contact"
    pageRef: "/contact"
    weight: 50

subfooter_one:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "Showcases"
    pageRef: "/showcases"
    weight: 20
  - name: "Diensten"
    pageRef: "/diensten"
    weight: 30

subfooter_two:
  - name: "Over mij"
    pageRef: "/over-mij"
    weight: 10
  - name: "Mijn klanten"
    pageRef: "/klanten"
    weight: 20
  - name: "Referenties"
    pageRef: "/referenties"
    weight: 30

footer:
  - name: "Algemene voorwaarden"
    pageRef: "/algemene-voorwaarden"
    weight: 10
  - name: "Privacy"
    pageRef: "/privacy"
    weight: 20