main:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "Showcases"
    pageRef: "/showcases"
    weight: 20
  - name: "Diensten"
    pageRef: "/diensten"
    weight: 30
  - parent: "Diensten"
    name: "Websites"
    pageRef: "/diensten/websites"
    weight: 1
  - parent: "Diensten"
    name: "Hosting"
    pageRef: "/diensten/hosting"
    weight: 2
  - parent: "Diensten"
    name: "Zoekmachine optimalisatie"
    pageRef: "/diensten/zoek-machine-optimalisatie"
    weight: 3
  - name: "Over mij"
    pageRef: "/over-mij"
    weight: 40
  - name: "Contact"
    pageRef: "/contact"
    weight: 50
  - name: "Start nu"
    pageRef: "/offerte"
    weight: 90
    params:
      button: true

services:
  - name: "Websites"
    pageRef: "/diensten/websites"
    weight: 10
  - name: "Hosting"
    pageRef: "/diensten/hosting"
    weight: 20
  - name: "Zoek machine optimalisatie"
    pageRef: "/diensten/zoek-machine-optimalisatie"
    weight: 30

internals:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "Over mij"
    pageRef: "/over-mij"
    weight: 20
  - name: "Showcases"
    pageRef: "/showcases"
    weight: 30

footer:
  - name: "Algemene voorwaarden"
    pageRef: "/algemene-voorwaarden"
    weight: 10
  - name: "Privacy"
    pageRef: "/privacy"
    weight: 20


