schema_type: "HomeAndConstructionBusiness"

# -- Basis informatie --
location: "Tilburg"
tagline: "Gewoon een goede website, zonder gebrul!"
description: "Krachtige, razendsnelle websites die scoren in Google. Geen technisch gedoe. Hosting, SEO en webdesign geregeld door jouw digitale gorilla: GorillaMade."

# -- Contact gegevens --
phone: "0613897425"
street_address: "Ooftbouwstraat 16"
city: "Tilburg"
postal_code: "5022 EC"
country: "NL"
area_served: "Tilburg en omgeving"
email: "hallo@gorillamade.nl"

# -- Geolocatie --
# latitude: 51.6816
# longitude: 5.0676

# -- Afbeeldingen --
logo: "/media/logo.png"
og_image: "/media/og-image.png"
site_logo: "/media/polklusbedrijf-logo.png"

# -- Social media profiles --
socials:
  - name: "nostr"
    icon: "/media/nostr-icon.svg"
    link: "nostr:npub1s4eztsvantqp72jh2ygzk8t4q9gwva8xkqdj83kha9dupyk23kwqmlya7j"

  - name: "github"
    icon: ""
    link: "https://github.com/GorillaMade"

  - name: "whatsapp"
    icon: ""
    link: "https://wa.me/0613897425?text=Ik%20ben%20geintresseerd%20in%20een%20website"

# -- Prijsrange (€, €€, €€€, €€€€) --
price_range: "€€"

# Google Tag Manager ID (optioneel)
# gtm_id: "GTM-XXXX"

# umami Website ID
umami_id: ""

# -- Openingstijden --
opening_hours:
  - day: "Maandag"
    opens: "09:00"
    closes: "17:00"
  - day: "Dinsdag"
    opens: "09:00"
    closes: "17:00"
  - day: "Woensdag"
    opens: "09:00"
    closes: "17:00"
  - day: "Donderdag"
    opens: "09:00"
    closes: "17:00"
  - day: "Vrijdag"
    opens: "09:00"
    closes: "17:00"