tagline: "Eén partner voor alles rond je website"

# -- Company --
company_name: "GorillaMade"
email: "hallo@gorillamade.nl"
phone: "0613897425"
chat_with_us:
  - name: "nostr"
    icon: "/media/icon-nostr.svg"
    link: "nostr:npub1s4eztsvantqp72jh2ygzk8t4q9gwva8xkqdj83kha9dupyk23kwqmlya7j"

  - name: "xmpp"
    icon: "/media/icon-xmpp.svg"
    link: "xmpp:gorillamade@jidme.nl"
  
  - name: "whatsapp"
    icon: ""
    link: "https://wa.me/0613897425?text=Ik%20ben%20geintresseerd%20in%20je%20website%20diensten"
  
# -- Address information --
street_address: "Ooftbouwstraat 16"
zipcode: "5022 EC"
city: "Tilburg"

# -- SocialMedia --
social_profiles:
  - name: "nostr"
    icon: "/media/icon-nostr.svg"
    link: "https://primal.net/p/npub1s4eztsvantqp72jh2ygzk8t4q9gwva8xkqdj83kha9dupyk23kwqmlya7j"

  - name: "linkedin"
    icon: ""
    link: "https://www.linkedin.com/in/timothy-remst"

  - name: "github"
    icon: ""
    link: "https://github.com/GorillaMade"

# -- Openingstijden --
opening_hours:
  - day: "Maandag"
    opens: "09:00"
    closes: "18:00"
  - day: "Dinsdag"
    opens: "09:00"
    closes: "18:00"
  - day: "Woensdag"
    opens: "09:00"
    closes: "18:00"
  - day: "Donderdag"
    opens: "09:00"
    closes: "18:00"
  - day: "Vrijdag"
    opens: "09:00"
    closes: "18:00"



# -- OpenGraph information --
og_image: "/media/gm-banner.png"


# -- Schema data --
schema:
  organisation:
    enabled: true
    context: "https://schema.org"
    type: "Organisation"
    name: "GorillaMade"
    url: "https://www.gorillamade.nl"
    logo: "https://www.gorillamade.nl/media/gm-logo.jpg"
    description: "Korte beschrijving van je bedrijf of website."
    sameAs:
      - "https://primal.net/p/npub1s4eztsvantqp72jh2ygzk8t4q9gwva8xkqdj83kha9dupyk23kwqmlya7j"
      - "https://www.linkedin.com/company/GorillaMade"
    address:
      type: "PostalAddress"
    contactPoint:
      type: "ContactPoint"
      telephone: "+31-6-13897425"
      contactType: "customer service"
      areaServed: "NL"
      availableLanguage: "Dutch"

  website:
    enabled: true
    context: "https://schema.org"
    type: "WebSite"
    name: "GorillaMade"
    url: "https://www.gorillamade.nl"
    potentialAction:
      type: "SearchAction"
      target: "https://www.gorillamade.nl/?s={search_term_string}"
      queryInput: "required name=search_term_string"

  