# -- Schema.org --
schema:
  localbusiness:
    name: "GorillaMade"
    url: "https://www.gorillamade.nl"
    logo: "/media/gorillamade-opengraph-image.webp"
    phone: "06123456778"
    email: "hallo@gorillamade.nl"
    street: "Ooftbouwstraat 16"
    city: "Tilburg"
    postalCode: "5022 EC"
    country: "NL"
    openingHours: "Mo-Fr 09:00-17:00"
    priceRange: "€€"
    description: "Digitale strategie en webdesign voor merken die impact willen maken."
    # geo:
    #   lat: 51.541029591719656
    #   lng: 5.091036569202518